import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern use of ToolNest AI.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-400">Last updated: August 23, 2026</p>

      <div className="mt-8 space-y-6 text-slate-600">
        <p>
          By using ToolNest AI, you agree to these terms. If you don't agree,
          please don't use the site.
        </p>

        <div>
          <h2 className="font-semibold text-slate-900">Use of the service</h2>
          <p className="mt-2">
            ToolNest AI provides AI-generated text tools for writing, content
            creation and productivity. You agree to use the service only for
            lawful purposes and not to submit content that is illegal, harmful,
            or infringes on others' rights.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">AI-generated content</h2>
          <p className="mt-2">
            Content generated by our tools is created by a third-party AI model
            (Google Gemini) and is provided "as is," without warranty of accuracy
            or completeness. You are responsible for reviewing and verifying any
            generated content before using or publishing it.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">No account, no guaranteed availability</h2>
          <p className="mt-2">
            The service currently requires no account. We do not guarantee
            uninterrupted availability and may modify, suspend, or discontinue
            tools at any time.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">Limitation of liability</h2>
          <p className="mt-2">
            ToolNest AI is provided without warranties of any kind. To the extent
            permitted by law, we are not liable for any damages arising from your
            use of the service or reliance on generated content.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">Changes to these terms</h2>
          <p className="mt-2">
            We may update these terms from time to time. Continued use of the site
            after changes means you accept the updated terms.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">Contact</h2>
          <p className="mt-2">
            Questions about these terms can be sent to Mahadeen81@gmail.com.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">Governing law</h2>
          <p className="mt-2">
            These terms are governed by the laws of the Hashemite Kingdom of Jordan.
          </p>
        </div>
      </div>
    </div>
  );
}
