import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern use of ToolNest AI.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-400">Last updated: [add date before launch]</p>

      <div className="mt-8 space-y-6 text-slate-600">
        <p>
          This is placeholder terms text. Have it reviewed before launch &mdash;
          it should reflect how your service actually works.
        </p>

        <div>
          <h2 className="font-semibold text-slate-900">Use of the service</h2>
          <p className="mt-2">
            Describe acceptable use of the AI tools, including that generated
            content should be reviewed before publishing and that users are
            responsible for how they use outputs.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">AI-generated content</h2>
          <p className="mt-2">
            Clarify that outputs are generated by a third-party AI model, may be
            inaccurate, and are provided "as is" without warranty.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-slate-900">Changes</h2>
          <p className="mt-2">
            State that these terms may be updated, and how users will be notified.
          </p>
        </div>
      </div>
    </div>
  );
}
